In [1]:
import numpy as np
import scipy.linalg
import mpmath

P = np.array([[3.53553e+2,  3.39645e+2, 2.77744e+2, -1.44946e+6],
              [-1.03528e+2, 2.33212e+1, 4.59607e+2, -6.3252e+5],
              [7.07107e-1, -3.53553e-1, 6.12372e-1, -9.18559e+2]])

def matrix_to_parameters( P):
    M = P[:,0:3]
    
    K,R = scipy.linalg.rq(M)
    
    T = np.diag(np.sign(np.diag(K)))
    
    if scipy.linalg.det(T) < 0:
        T[1,1] *= -1
    
    K = np.dot(K,T)
    R = np.dot(T,R)
    
    C = np.dot(scipy.linalg.inv(-M),P[:,3])
    
    alpha=K[0][0]
    x0=K[0][2]
    y0=K[1][2]
    tan_theta=K[0][0]/(-K[0][1])
    theta=mpmath.atan(tan_theta)
    print(alpha)
    print("the difference between the  centre of camera coordinate frame and the image center along the x axis",x0)
    print("the difference between the  centre of camera coordinate frame and the image center along the y axis",y0)
  
    sin_theta=mpmath.sin(theta)
    beta=K[1][1]*sin_theta
  
    T=-(np.dot(R,C))
    fx=K[0][0]
    fy=K[1][1]
    s=K[0][1]
    print("intrinsic camera matrix",K)
    print("Translation matrix ",T)
    print("Rotation matrix",R)
  
    print("camera focal length in the x axis in pixels",fx)
    print("camera focal length in the y axis in pixels",fy)
    print("skew parameter",s)
    print("The angle between the x-axis and y-axis in the image plane",theta)


   


matrix_to_parameters(P)



468.164671277965
the difference between the  centre of camera coordinate frame and the image center along the x axis 300.0000163077135
the difference between the  centre of camera coordinate frame and the image center along the y axis 199.9998541201699
intrinsic camera matrix [[468.16467128  91.22505222 300.00001631]
 [  0.         427.20086371 199.99985412]
 [  0.           0.           0.99999975]]
Translation matrix  [-2302.72199352 -1050.57907454  -918.5592298 ]
Rotation matrix [[ 0.41380237  0.90914861  0.04707869]
 [-0.57338211  0.22011137  0.78916661]
 [ 0.70710718 -0.35355309  0.61237215]]
camera focal length in the x axis in pixels 468.164671277965
camera focal length in the y axis in pixels 427.20086370974354
skew parameter 91.22505222013655
The angle between the x-axis and y-axis in the image plane -1.37835104334233
